#! /usr/bin/env bash

brewPrefix=$($HOME/.scripts/posix/getBrewPrefix)

if [[ ! -z "$brewPrefix" ]] && [[ -r "$brewPrefix/etc/profile.d/bash_completion.sh" ]]; then
  . "$brewPrefix/etc/profile.d/bash_completion.sh"
fi
