#! /usr/bin/env zsh

# GPG
# Requires stdin
export GPG_TTY=$(tty)

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# START NO OUTPUT

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# CASE_SENSITIVE="false"

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Fix root shell (ohmyzsh/ohmyzsh#4426)
ZSH_DISABLE_COMPFIX="true"

# Stop oh-my-zsh update prompt
DISABLE_AUTO_UPDATE=true

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-better-npm-completion zsh-completions zsh-nvm zsh-syntax-highlighting zsh-vs-code-integration)

# Special terminal features
POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
ITERM_SHELL_INTEGRATION_INSTALLED="Yes"

# Oh My Zsh Theme
ZSH_THEME="powerlevel10k/powerlevel10k"
# Must occur after package manager completions and oh-my-zsh init
export FPATH="$HOME/.scripts/.completion/zsh/overrides:${FPATH}"

# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
export NVM_COMPLETION=true
export NVM_AUTO_USE=true

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Options
unsetopt LIST_BEEP

# Ensure key is defined
(( $+key )) || declare -A key
(( $+key[Up] )) || key[Up]="$terminfo[kcuu1]"
(( $+key[Down] )) || key[Down]="$terminfo[kcud1]"

# Keybindings
bindkey "${key[Up]}" up-line-or-beginning-search
bindkey "${key[Down]}" down-line-or-beginning-search

# Additional completions
# Replaced by plugin
# type npm &>/dev/null && source <(npm completion)

GIT_UPDATE_FOLDERS=(  )

export LESS="-R"
if type code &>/dev/null; then
  export VISUAL="/usr/bin/env code --wait --new-window"
fi
if type nvim &>/dev/null; then
  export EDITOR="/usr/bin/env nvim"
fi

# Aliases
alias mkdir="mkdir -p"
# I'm hopeless
alias ehco="echo"
# No copyright statement on startup
alias pwsh="pwsh -NoLogo"

# Watch update frequency
export WATCH_INTERVAL=0.2

# Homebrew update frequency
export HOMEBREW_AUTO_UPDATE_SECS="300" # 5 minutes

# Ignore completion cache
zstyle ":completion:*:commands" rehash 1

unset brewCompletionPath 
