#! /usr/bin/env zsh

if type brew &>/dev/null; then
  # Get values
  values=()
  for string in $(ls $(brew --prefix)/opt | grep python@3. ); do
    [[ $string =~ 'python@3.([0-9]+)' ]]
    values+=$match
  done

  # Sort
  echo "python@3."$(printf '%s\n' "${values[@]}" |
  awk '$1 > m || NR == 1 { m = $1 } END { print m }')
fi
